import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "nextjs, react, typescript",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="h-[60px] p-4 w-full bg-black grid items-center">
          <nav className="flex justify-between text-white">
            <h1 className="text-2xl">Next blog</h1>

            <ul className="flex items-center">
              <li className="mr-4">
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
              <li className="ml-4">
                <Link href="/users">See users</Link>
              </li>
              <div className="flex ml-4 items-center justify-center">
                <li className="mr-4 text-[#037fff]">
                  <Link href="/login">Login</Link>
                </li>
                <li>
                  <Link href="/signup">Signup</Link>
                </li>
              </div>
            </ul>
          </nav>
        </header>
        <main className="mt-[1rem]">{children}</main>
      </body>
    </html>
  );
}
